import {
  ActivityHeartbeat,
  Affiliate,
  Album,
  AlertTriangle,
  ApiBook,
  ArrowDown,
  ArrowUp,
  Bell,
  Book,
  BrandDingtalk,
  BrandWechat,
  BuildingStore,
  Calendar,
  ChartBar,
  ChartHistogram,
  Check,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronsLeft,
  ChevronsRight,
  CircleCheck,
  Clock,
  Coins,
  Copy,
  CreditCard,
  CreditCardPay,
  DeviceDesktopAnalytics2,
  DeviceFloppy,
  DeviceLaptop,
  Download,
  Eye,
  EyeOff,
  ExternalLink,
  Filter,
  Gift,
  GiftCard,
  Gauge,
  Home,
  Hourglass,
  ImageSpark,
  InfoCircle,
  Key,
  Language,
  LayoutDashboard,
  LayoutGrid,
  Link,
  Logout,
  Mail,
  Menu2,
  MessageCircle,
  Moon,
  MoonStars,
  Network,
  Pencil,
  Photo,
  PlayerPause,
  PlayerPlay,
  Plus,
  Receipt,
  ReceiptDollar,
  Refresh,
  Restore,
  Route,
  Search,
  Send,
  Server,
  ServerBolt,
  Settings,
  ShieldCheck,
  ShoppingCart,
  Speakerphone,
  Sun,
  SunHigh,
  Terminal2,
  Trash,
  Upload,
  User,
  Users,
  Wallet,
  Wifi,
  World,
  Wrench,
  X,
} from "@appica/icons-react";

const icons = {
  affiliate: Affiliate,
  announcement: Speakerphone,
  apiBook: ApiBook,
  apiKey: Key,
  arrowDown: ArrowDown,
  arrowUp: ArrowUp,
  batchImages: Album,
  bell: Bell,
  book: Book,
  dingtalk: BrandDingtalk,
  calendar: Calendar,
  card: CreditCard,
  cart: ShoppingCart,
  channel: Wifi,
  channelNetwork: Network,
  chart: ChartBar,
  chat: MessageCircle,
  check: Check,
  chevronDown: ChevronDown,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  chevronsLeft: ChevronsLeft,
  chevronsRight: ChevronsRight,
  circleCheck: CircleCheck,
  clock: Clock,
  close: X,
  coins: Coins,
  copy: Copy,
  dashboard: LayoutDashboard,
  dashboardAnalytics: DeviceDesktopAnalytics2,
  cache: DeviceFloppy,
  dollar: Wallet,
  download: Download,
  edit: Pencil,
  external: ExternalLink,
  eye: Eye,
  eyeOff: EyeOff,
  filter: Filter,
  gift: Gift,
  giftCard: GiftCard,
  gauge: Gauge,
  globe: World,
  grid: LayoutGrid,
  home: Home,
  hourglass: Hourglass,
  image: Photo,
  imageStudio: ImageSpark,
  info: InfoCircle,
  key: Key,
  language: Language,
  laptop: DeviceLaptop,
  link: Link,
  logout: Logout,
  mail: Mail,
  menu: Menu2,
  monitor: Server,
  moon: Moon,
  moonStars: MoonStars,
  order: Receipt,
  orderReceipt: ReceiptDollar,
  pause: PlayerPause,
  play: PlayerPlay,
  plus: Plus,
  pulse: ActivityHeartbeat,
  refresh: Refresh,
  reset: Restore,
  search: Search,
  send: Send,
  serverHealth: ServerBolt,
  settings: Settings,
  shield: ShieldCheck,
  storefront: BuildingStore,
  sun: Sun,
  sunHigh: SunHigh,
  terminal: Terminal2,
  trash: Trash,
  upload: Upload,
  usageChart: ChartHistogram,
  user: User,
  users: Users,
  walkthrough: Route,
  wallet: Wallet,
  walletTopUp: CreditCardPay,
  warning: AlertTriangle,
  wechat: BrandWechat,
  wrench: Wrench,
};

export function Icon({ name, size = 20, className = "", ...props }) {
  const Component = icons[name] || InfoCircle;
  return <Component className={className} size={size} strokeWidth={1.75} {...props} />;
}
